version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t bennycheng/frontend -f Dockerfile.dev .
      - run:
          name: Test application Docker image
          command: |
            docker run bennycheng/frontend npm run test:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
